# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mecho < Formula
  desc ""
  homepage "https://github.com/ozanuslan/mecho"
  version "0.1"

  on_macos do
    url "https://github.com/ozanuslan/mecho/releases/download/v0.1/mecho_0.1_darwin_all.tar.gz"
    sha256 "615414bf8364f87bfaabe758adf5aa206af6f1a76bd216bd236de589189c8206"

    def install
      bin.install "mecho"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ozanuslan/mecho/releases/download/v0.1/mecho_0.1_linux_amd64.tar.gz"
      sha256 "589a30dfed176f07eec0669e6a70f5ed5d289b168ca5a41e7ee0a55af238cc86"

      def install
        bin.install "mecho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ozanuslan/mecho/releases/download/v0.1/mecho_0.1_linux_arm64.tar.gz"
      sha256 "0468a8a466edda5040dd904f7f8027a8334854e3b8e572b6449e589c0ad23429"

      def install
        bin.install "mecho"
      end
    end
  end
end
